sonar.organization=chawlamuskan
sonar.projectKey=chawlamuskan_sopra-fs26-group-33-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./src